import { NextRequest, NextResponse } from 'next/server'
import { verifyAndDecodeRecordingUrl } from '@/lib/recording-proxy'
import { checkRateLimit, clientIp } from '@/lib/rate-limit'

/**
 * GET /api/recordings/proxy?u=<base64url>&s=<base64url>
 *
 * Streams a call recording from the (IP-whitelisted) origin (Vicitel)
 * back to any client. The (u, s) pair is generated by
 * signRecordingUrl() inside the Hub when an appointment alert
 * fires — the signature ties the URL to our secret so attackers
 * can't construct one for an arbitrary recording.
 *
 * Public route (middleware whitelist). Authenticating clients here
 * doesn't make sense — recipients are typically external client
 * Slack channels or email recipients who don't have Hub accounts.
 * Security is via the HMAC signature + host allowlist; the rate
 * limit caps damage if a URL leaks.
 *
 * Range header passthrough so HTML5 audio players can seek; we
 * propagate the upstream status (206 Partial Content) + relevant
 * headers (Content-Range, Accept-Ranges, Content-Length) so the
 * browser thinks it's talking to a regular media server.
 */

/** Per-IP play budget. 60 plays/hr is generous for normal use
 *  (an SDR re-listening before a meeting) but caps the blast radius
 *  if a signed URL leaks to a bot or someone tries to scrape every
 *  recording they were ever sent. */
const RATE_LIMIT_PER_IP = 60
const RATE_LIMIT_WINDOW_MS = 60 * 60 * 1000

export async function GET(req: NextRequest) {
  // Rate limit BEFORE signature verification — we don't want to
  // give an attacker a free way to probe whether a (u, s) pair is
  // valid without consuming their quota.
  const ip = clientIp(req)
  const rl = checkRateLimit(
    `recording-proxy:${ip}`,
    RATE_LIMIT_PER_IP,
    RATE_LIMIT_WINDOW_MS,
  )
  if (!rl.ok) {
    return NextResponse.json(
      { error: 'rate-limited — try again later' },
      {
        status: 429,
        headers: { 'retry-after': String(Math.ceil(rl.retryAfterMs / 1000)) },
      },
    )
  }

  const u = req.nextUrl.searchParams.get('u') || ''
  const s = req.nextUrl.searchParams.get('s') || ''
  if (!u || !s) {
    return NextResponse.json({ error: 'missing params' }, { status: 400 })
  }

  const originalUrl = verifyAndDecodeRecordingUrl(u, s)
  if (!originalUrl) {
    // 404 instead of 403 so an attacker can't tell apart "the
    // signature is wrong" from "the recording isn't here" —
    // matches what S3 does for missing/bad-signature objects.
    return NextResponse.json({ error: 'not found' }, { status: 404 })
  }

  // Pass through the Range header so audio seeking works in the
  // browser. Most other request headers we deliberately drop —
  // we don't want to leak the client's User-Agent or cookies
  // upstream. Range is the one media players need.
  const upstreamHeaders: Record<string, string> = {}
  const range = req.headers.get('range')
  if (range) upstreamHeaders['range'] = range

  let upstream: Response
  try {
    upstream = await fetch(originalUrl, {
      method: 'GET',
      headers: upstreamHeaders,
      // Don't follow redirects automatically — the original URL is
      // signed, but redirects could go anywhere and we'd be acting
      // as an open proxy. Pretty much never happens with vicitel
      // but defense in depth.
      redirect: 'manual',
    })
  } catch (err) {
    console.error('[recordings/proxy] upstream fetch failed:', err)
    return NextResponse.json(
      { error: 'upstream unreachable' },
      { status: 502 },
    )
  }

  // Don't proxy redirects, errors, or other non-2xx. If vicitel
  // returns 403, the client gets 403 too — that almost certainly
  // means our IPs aren't on the allowlist yet (the infra step).
  // Body is forwarded so a debugging admin can read whatever
  // vicitel said.
  if (upstream.status >= 400 || upstream.status === 0) {
    const body = await upstream.text().catch(() => '')
    return new NextResponse(body || 'upstream error', {
      status: upstream.status || 502,
      headers: {
        'content-type': upstream.headers.get('content-type') || 'text/plain',
      },
    })
  }
  if (upstream.status >= 300 && upstream.status < 400) {
    // Redirect — refuse rather than chase. See note above.
    return NextResponse.json(
      { error: 'upstream redirect refused' },
      { status: 502 },
    )
  }

  // Build the response. Pass through media-relevant headers so the
  // browser can stream + seek. We drop the rest (set-cookie etc.)
  // so we don't leak vicitel internals.
  const responseHeaders: Record<string, string> = {}
  const passthrough = [
    'content-type',
    'content-length',
    'content-range',
    'accept-ranges',
    'last-modified',
    'etag',
  ]
  for (const h of passthrough) {
    const v = upstream.headers.get(h)
    if (v) responseHeaders[h] = v
  }
  if (!responseHeaders['content-type']) {
    responseHeaders['content-type'] = 'audio/mpeg'
  }
  // Cache aggressively at the browser — recordings don't change.
  // If a recording does need to be re-downloaded (e.g. vicitel
  // overwrites it, unlikely), an Etag mismatch will refresh.
  responseHeaders['cache-control'] = 'private, max-age=3600'

  // Stream the body straight through without buffering — Next.js
  // accepts a ReadableStream as the response body and pipes it.
  // For small files (a few MB) this is basically a copy through
  // the runtime; for larger files it keeps memory bounded.
  return new NextResponse(upstream.body, {
    status: upstream.status,
    headers: responseHeaders,
  })
}
